version: "3.5"

networks:
  mqtt:

volumes:
  mqtt:

secrets:
  # Secrets format
  # ${service_name}_${mount_point}:
  #   name: ${STACK_NAME:-technocore}_${service_name}_${mount_point}
  # #   external: true
  vernemq_admin_password:
    name: ${STACK_NAME:-technocore}_vernemq_admin_password
    external: true

services:
  ingress:
    networks:
      - mqtt

  mqtt:
    deploy:
      labels:
      #  # These env vars should infact be uppercase
      #  - traefik.frontend.rule=$MQTT_ROUTING_LABEL
      #  - traefik.frontend.priority=$MQTT_ROUTING_LABEL_PRIORITY
      #  - traefik.port=SET_ME_PLEASE
      #  - ${TRAEFIK_BASIC_AUTH}
      #  - traefik.enable=true
      #  # You'll need to set applicaiton's port here.
      #  - traefik.tags=ingress 
      #  - traefik.docker.network=${STACK_NAME:-technocore}_mqtt
      #  # Traefik service that listens to HTTP
      #  - traefik.redirectorservice.frontend.entryPoints=http
      #  - traefik.redirectorservice.frontend.redirect.entryPoint=https
      #  # Traefik service that listens to HTTPS
      #  - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - ADMIN_USER=${ADMIN_USER}

    image: ${image_provider:-scififarms}/technocore-vernemq:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      mqtt:
        aliases:
          - mqtt.local
    hostname: mqtt
    secrets:
      - source: vernemq_admin_password
        target: admin_password
      - source: mqtt_db_mqtt_username
        target: mqtt_username
      - source: mqtt_db_mqtt_password
        target: mqtt_password
    volumes:
      - mqtt:/vernemq/etc 
